Patch 6
swisscom/docs-appcloud-devguide pull request #17
Opened 2017-08-24 08:04 UTC by rumpli

next cf release, including now the buildpacks in the release notes

2017-08-24 08:22 UTC, cloudlena requested changes

2017-08-24 08:22 UTC, mastertinner commented on release-notes.html.md.erb
> +Release date: xx.xx.2017
Please fill in the release date

2017-08-24 13:48 UTC, rumpli commented on release-notes.html.md.erb
> +Release date: xx.xx.2017
Will follow as soon the date is known. 👍

2017-08-24 18:34 UTC, mastertinner commented on release-notes.html.md.erb
> +Release date: xx.xx.2017
Ok. Let's wait with merging until then.

2017-09-15 12:58 UTC, rumpli commented
Release date is now fixed.

2017-09-16 10:06 UTC, cloudlena approved these changes

2017-09-16 10:06 UTC, merged

2017-09-16 10:06 UTC, mastertinner commented
Thanks, @rumpli!